import {
  getBikePhysicsProfile,
} from "@/domain/physics/catalog";
import type {
  BikePhysicsProfile,
  CadenceResult,
  PhysicsBikeResult,
  PhysicsBreakdown,
  PhysicsScenario,
} from "@/engine/physics/types";

export const GRAVITY_MPS2 = 9.80665;

function gradeAngle(gradePercent: number) {
  return Math.atan(gradePercent / 100);
}

function windMps(windSpeedKph: number) {
  return windSpeedKph / 3.6;
}

export function calculatePhysicsBreakdown(
  speedMps: number,
  profile: BikePhysicsProfile,
  scenario: PhysicsScenario,
): PhysicsBreakdown {
  const speed = Math.max(0, speedMps);
  const totalMassKg =
    Math.max(0, scenario.riderMassKg) +
    Math.max(0, scenario.cargoMassKg) +
    profile.bikeMassKg;

  const angle = gradeAngle(scenario.gradePercent);
  const normalForceN =
    totalMassKg * GRAVITY_MPS2 * Math.cos(angle);

  const crr = profile.rollingResistance[scenario.surfaceId];
  const rollingForceN = crr * normalForceN;
  const gravityForceN =
    totalMassKg * GRAVITY_MPS2 * Math.sin(angle);

  // Positive wind = headwind. Negative wind = tailwind.
  // Signed relative air speed lets a tailwind faster than the bicycle
  // produce a forward aerodynamic force rather than impossible drag.
  const relativeAirSpeedMps = speed + windMps(scenario.windSpeedKph);
  const aeroForceN =
    0.5 *
    scenario.airDensityKgM3 *
    profile.cdaM2 *
    relativeAirSpeedMps *
    Math.abs(relativeAirSpeedMps);

  const rollingPowerW = rollingForceN * speed;
  const gravityPowerW = gravityForceN * speed;
  const aeroPowerW = aeroForceN * speed;
  const requiredWheelPowerW =
    rollingPowerW + gravityPowerW + aeroPowerW;

  const requiredRiderPowerW =
    requiredWheelPowerW >= 0
      ? requiredWheelPowerW / profile.drivetrainEfficiency
      : requiredWheelPowerW;

  return {
    speedMps: speed,
    speedKph: speed * 3.6,
    totalMassKg,
    wheelPowerW:
      Math.max(0, scenario.riderPowerW) *
      profile.drivetrainEfficiency,
    rollingForceN,
    gravityForceN,
    aeroForceN,
    rollingPowerW,
    gravityPowerW,
    aeroPowerW,
    requiredWheelPowerW,
    requiredRiderPowerW,
    relativeAirSpeedMps,
  };
}

function totalResistingForce(
  speedMps: number,
  profile: BikePhysicsProfile,
  scenario: PhysicsScenario,
) {
  const breakdown = calculatePhysicsBreakdown(
    speedMps,
    profile,
    scenario,
  );
  return (
    breakdown.rollingForceN +
    breakdown.gravityForceN +
    breakdown.aeroForceN
  );
}

function powerResidual(
  speedMps: number,
  profile: BikePhysicsProfile,
  scenario: PhysicsScenario,
) {
  const breakdown = calculatePhysicsBreakdown(
    speedMps,
    profile,
    scenario,
  );
  return breakdown.wheelPowerW - breakdown.requiredWheelPowerW;
}

function bisectRoot(
  fn: (value: number) => number,
  low: number,
  high: number,
  iterations = 72,
) {
  let lo = low;
  let hi = high;
  let flo = fn(lo);
  let fhi = fn(hi);

  if (flo === 0) return lo;
  if (fhi === 0) return hi;
  if (flo * fhi > 0) return null;

  for (let index = 0; index < iterations; index += 1) {
    const mid = (lo + hi) / 2;
    const fmid = fn(mid);

    if (Math.abs(fmid) < 1e-8) return mid;

    if (flo * fmid <= 0) {
      hi = mid;
      fhi = fmid;
    } else {
      lo = mid;
      flo = fmid;
    }
  }

  return (lo + hi) / 2;
}

export function solveSteadySpeedMps(
  profile: BikePhysicsProfile,
  scenario: PhysicsScenario,
) {
  const maxSpeedMps = 60;

  if (scenario.riderPowerW <= 0) {
    const forceAtRest = totalResistingForce(0, profile, scenario);

    // On flat/uphill terrain with no rider power there is no positive
    // steady-state speed generated by the bicycle itself.
    if (forceAtRest >= 0) return 0;

    const root = bisectRoot(
      (speed) => totalResistingForce(speed, profile, scenario),
      0.0001,
      maxSpeedMps,
    );
    return root ?? maxSpeedMps;
  }

  const root = bisectRoot(
    (speed) => powerResidual(speed, profile, scenario),
    0,
    maxSpeedMps,
  );

  return root ?? maxSpeedMps;
}

export function simulateProfile(
  profile: BikePhysicsProfile,
  scenario: PhysicsScenario,
): PhysicsBikeResult {
  const speedMps = solveSteadySpeedMps(profile, scenario);
  const breakdown = calculatePhysicsBreakdown(
    speedMps,
    profile,
    scenario,
  );

  return {
    bikeId: profile.bikeId,
    crr: profile.rollingResistance[scenario.surfaceId],
    profile,
    ...breakdown,
  };
}

export function simulateBike(
  bikeId: string,
  scenario: PhysicsScenario,
): PhysicsBikeResult | null {
  const profile = getBikePhysicsProfile(bikeId);
  if (!profile) return null;
  return simulateProfile(profile, scenario);
}

export function cadenceSpeed(
  cadenceRpm: number,
  driveRatio: number,
  wheelCircumferenceM: number,
): CadenceResult {
  const safeCadence = Math.max(0, cadenceRpm);
  const safeRatio = Math.max(0, driveRatio);
  const safeCircumference = Math.max(0, wheelCircumferenceM);

  const wheelRevolutionsPerMinute = safeCadence * safeRatio;
  const speedMPerMinute =
    wheelRevolutionsPerMinute * safeCircumference;

  return {
    speedKph: (speedMPerMinute * 60) / 1000,
    cadenceRpm: safeCadence,
    driveRatio: safeRatio,
    wheelCircumferenceM: safeCircumference,
  };
}

export function cadenceForSpeed(
  speedKph: number,
  driveRatio: number,
  wheelCircumferenceM: number,
) {
  if (driveRatio <= 0 || wheelCircumferenceM <= 0) return 0;
  const speedMPerMinute = (Math.max(0, speedKph) * 1000) / 60;
  const wheelRpm = speedMPerMinute / wheelCircumferenceM;
  return wheelRpm / driveRatio;
}
