const ROAD_R1_INTERACTIVE = new Set([
  "bike.road.r1.frame",
  "bike.road.r1.fork",
  "bike.road.r1.headset",
  "bike.road.r1.front-wheel",
  "bike.road.r1.rear-wheel",
  "bike.road.r1.front-tire",
  "bike.road.r1.rear-tire",
  "bike.road.r1.front-rim",
  "bike.road.r1.rear-rim",
  "bike.road.r1.front-hub",
  "bike.road.r1.rear-hub",
  "bike.road.r1.front-rotor",
  "bike.road.r1.rear-rotor",
  "bike.road.r1.front-caliper",
  "bike.road.r1.rear-caliper",
  "bike.road.r1.rear-thru-axle",
  "bike.road.r1.handlebar",
  "bike.road.r1.stem",
  "bike.road.r1.saddle",
  "bike.road.r1.seatpost",
  "bike.road.r1.crankset",
  "bike.road.r1.large-chainring",
  "bike.road.r1.chain",
  "bike.road.r1.cassette",
  "bike.road.r1.rear-derailleur",
  "bike.road.r1.left-pedal",
  "bike.road.r1.right-pedal",
]);

const MTB_M1_INTERACTIVE = new Set([
  "bike.mtb.m1.frame",
  "bike.mtb.m1.fork",
  "bike.mtb.m1.rear-shock",
  "bike.mtb.m1.suspension-linkage",
  "bike.mtb.m1.headset",
  "bike.mtb.m1.handlebar",
  "bike.mtb.m1.stem",
  "bike.mtb.m1.front-wheel",
  "bike.mtb.m1.rear-wheel",
  "bike.mtb.m1.front-tire",
  "bike.mtb.m1.rear-tire",
  "bike.mtb.m1.front-rim",
  "bike.mtb.m1.rear-rim",
  "bike.mtb.m1.front-hub",
  "bike.mtb.m1.rear-hub",
  "bike.mtb.m1.front-rotor",
  "bike.mtb.m1.rear-rotor",
  "bike.mtb.m1.front-caliper",
  "bike.mtb.m1.rear-caliper",
  "bike.mtb.m1.crankset",
  "bike.mtb.m1.chainring",
  "bike.mtb.m1.chain",
  "bike.mtb.m1.cassette",
  "bike.mtb.m1.rear-derailleur",
  "bike.mtb.m1.saddle",
  "bike.mtb.m1.dropper-post",
  "bike.mtb.m1.left-pedal",
  "bike.mtb.m1.right-pedal",
  "bike.mtb.m1.front-thru-axle",
  "bike.mtb.m1.rear-thru-axle",
]);

const URBAN_U1_INTERACTIVE = new Set([
  "bike.urban.u1.frame",
  "bike.urban.u1.fork",
  "bike.urban.u1.headset",
  "bike.urban.u1.handlebar",
  "bike.urban.u1.stem",
  "bike.urban.u1.left-grip",
  "bike.urban.u1.right-grip",
  "bike.urban.u1.front-wheel",
  "bike.urban.u1.rear-wheel",
  "bike.urban.u1.front-tire",
  "bike.urban.u1.rear-tire",
  "bike.urban.u1.front-rim",
  "bike.urban.u1.rear-rim",
  "bike.urban.u1.front-hub",
  "bike.urban.u1.rear-hub",
  "bike.urban.u1.front-rotor",
  "bike.urban.u1.rear-rotor",
  "bike.urban.u1.front-caliper",
  "bike.urban.u1.rear-caliper",
  "bike.urban.u1.crankset",
  "bike.urban.u1.chainring",
  "bike.urban.u1.chain",
  "bike.urban.u1.rear-sprocket",
  "bike.urban.u1.chain-guard",
  "bike.urban.u1.saddle",
  "bike.urban.u1.seatpost",
  "bike.urban.u1.left-pedal",
  "bike.urban.u1.right-pedal",
  "bike.urban.u1.front-fender",
  "bike.urban.u1.rear-fender",
  "bike.urban.u1.rear-rack",
  "bike.urban.u1.front-light",
  "bike.urban.u1.rear-light",
  "bike.urban.u1.kickstand",
  "bike.urban.u1.frame-lock",
  "bike.urban.u1.bell",
  "bike.urban.u1.front-axle",
  "bike.urban.u1.rear-axle",
]);

const GRAVEL_G1_INTERACTIVE = new Set([
  "bike.gravel.g1.frame",
  "bike.gravel.g1.fork",
  "bike.gravel.g1.headset",
  "bike.gravel.g1.handlebar",
  "bike.gravel.g1.stem",
  "bike.gravel.g1.left-shifter",
  "bike.gravel.g1.right-shifter",
  "bike.gravel.g1.front-wheel",
  "bike.gravel.g1.rear-wheel",
  "bike.gravel.g1.front-tire",
  "bike.gravel.g1.rear-tire",
  "bike.gravel.g1.front-rim",
  "bike.gravel.g1.rear-rim",
  "bike.gravel.g1.front-hub",
  "bike.gravel.g1.rear-hub",
  "bike.gravel.g1.front-rotor",
  "bike.gravel.g1.rear-rotor",
  "bike.gravel.g1.front-caliper",
  "bike.gravel.g1.rear-caliper",
  "bike.gravel.g1.saddle",
  "bike.gravel.g1.seatpost",
  "bike.gravel.g1.crankset",
  "bike.gravel.g1.chainring",
  "bike.gravel.g1.bottom-bracket",
  "bike.gravel.g1.chain",
  "bike.gravel.g1.cassette",
  "bike.gravel.g1.rear-derailleur",
  "bike.gravel.g1.left-pedal",
  "bike.gravel.g1.right-pedal",
  "bike.gravel.g1.front-thru-axle",
  "bike.gravel.g1.rear-thru-axle",
  "bike.gravel.g1.frame-mounts",
  "bike.gravel.g1.fork-mounts",
  "bike.gravel.g1.downtube-protector",
]);

const BY_BIKE = new Map<string, ReadonlySet<string>>([
  ["bike.road.r1", ROAD_R1_INTERACTIVE],
  ["bike.mtb.m1", MTB_M1_INTERACTIVE],
  ["bike.urban.u1", URBAN_U1_INTERACTIVE],
  ["bike.gravel.g1", GRAVEL_G1_INTERACTIVE],
]);

export function getInteractiveComponentIds(bikeId: string) {
  return BY_BIKE.get(bikeId) ?? new Set<string>();
}

export function isInteractiveComponent(
  bikeId: string,
  componentId: string,
) {
  return getInteractiveComponentIds(bikeId).has(componentId);
}

// Backwards-compatible export for Road R1 content validation.
export const CALIBRATION_COMPONENT_IDS = ROAD_R1_INTERACTIVE;
